// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © wangyanchaoace

//@version=5
indicator("Ema together", overlay = true)
sma20 = ta.sma(close, 20)
sma60 = ta.sma(close, 60)
sma120 = ta.sma(close, 120)
ema20 = ta.ema(close, 20)
ema60 = ta.ema(close, 60)
ema120 = ta.ema(close, 120)

plot(sma20, "sma20", color = color.new(color.blue, 0), linewidth = 3)
plot(ema20, "ema20", color = color.new(color.red, 0), linewidth = 3)

plot(sma60, "sma60", color = #57a9ec, linewidth = 2)
plot(ema60, "ema60", color = #f57d7d, linewidth = 2)

plot(sma120,"sma120", color = #bad0e3, linewidth = 2, style = plot.style_cross)
plot(ema120,"ema120", color = #f6bdbd, linewidth = 2, style = plot.style_cross)
