// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © wangyanchaoace

//@version=5
strategy("emaStrategyV1", overlay=true, initial_capital = 1000, default_qty_value = 100, default_qty_type = strategy.percent_of_equity, commission_value = 0.025)

fastPeriod = input(defval = 24 , title = "Fast MA")
slowPeriod = input(defval = 200, title = "Slow MA")

fastEma = ta.ema(close, fastPeriod)
fastSma = ta.sma(close, fastPeriod)
slowEma = ta.ema(close, slowPeriod)
plot(fastEma, color = color.blue)
plot(slowEma, color = #1976c7)
plot(fastSma, color = color.red)
//  atr, average true range. 是近期每天价格波动(最高价-最低价)的平均值
atr = ta.atr(14)

longInBigPeriod = fastEma > slowEma
longInSmallPeriod = fastEma > fastSma
exitInBigPeriod = fastEma < slowEma
// 是否要利用fastEma 和 fastSma , 毕竟小于 slowEma的时候已经太晚了
exitInSmallPeriod = close < slowEma
timePeriod = time >= timestamp(syminfo.timezone, 2020, 12, 15, 0, 0)
inTrade = strategy.position_size > 0
notInTrade = strategy.position_size <= 0


if timePeriod and longInBigPeriod and longInSmallPeriod and notInTrade
// 看下strategy.entry("long", strategy.long, when=notInTrade)
    strategy.entry("long", strategy.long)
    stopLoss = close - atr * 3
    strategy.exit("exit", "long", stop = stopLoss)

// 看下不设置该关闭是否有问题
if exitInBigPeriod and exitInSmallPeriod and inTrade
    strategy.close(id = "long")
bgcolor(notInTrade ? color.white : color.new(color.green, 90))



// // 如果不根据notInTrade判断的话, 可能会出现slowEma和fastEma重新交叉之后, 更新了exit的价格, 影响当前在途的价格单
// if longCondition1 and timePeriod and notInTrade
//     stopLoss = low * 0.97
//     takeProfit = high * 1.12
//     strategy.entry('long', strategy.long)
//     strategy.exit('exit', 'long', stop = stopLoss, limit = takeProfit)
//     log.info("buy at price:{0}, stop at price:{1}, takeProfit at price:{2}", close, stopLoss, takeProfit)

// plot(fastEma, color = color.new(color.green, 0))
// plot(slowEma, color = color.new(color.red, 0))


// // longCondition = ta.crossover(ta.sma(close, 14), ta.sma(close, 28))
// // if (longCondition)
// //     strategy.entry("My Long Entry Id", strategy.long)

// // shortCondition = ta.crossunder(ta.sma(close, 14), ta.sma(close, 28))
// // if (shortCondition)
// //     strategy.entry("My Short Entry Id", strategy.short)