// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © wangyanchaoace

//@version=5
strategy("emaStrategyV3ByYueYue", overlay=true, initial_capital = 1000, default_qty_value = 100, default_qty_type = strategy.percent_of_equity, commission_value = 0.025)

fastPeriod = input(defval = 20 , title = "Fast MA")

fastEma = ta.ema(close, fastPeriod)
// fastSma = ta.sma(close, fastPeriod)
plot(fastEma, color = color.blue)
// plot(fastSma, color = #1976c7)

atr = ta.atr(14)

longInSmallPeriod = close > fastEma
longWithBigCandle = (high - low) > atr * 1.5
exitInBigPeriod = close < fastEma
timePeriod = time >= timestamp(syminfo.timezone, 2024, 1, 15, 0, 0)
inTrade = strategy.position_size > 0
notInTrade = strategy.position_size <= 0


if timePeriod and longInSmallPeriod and longWithBigCandle and notInTrade
    strategy.entry("long", strategy.long)
    stopLoss = close - atr * 3
    strategy.exit("exit", "long", stop = stopLoss)

if exitInBigPeriod and inTrade
    strategy.close(id = "long")
bgcolor(notInTrade ? color.white : color.new(color.green, 90))



// // 如果不根据notInTrade判断的话, 可能会出现slowEma和fastEma重新交叉之后, 更新了exit的价格, 影响当前在途的价格单
// if longCondition1 and timePeriod and notInTrade
//     stopLoss = low * 0.97
//     takeProfit = high * 1.12
//     strategy.entry('long', strategy.long)
//     strategy.exit('exit', 'long', stop = stopLoss, limit = takeProfit)
//     log.info("buy at price:{0}, stop at price:{1}, takeProfit at price:{2}", close, stopLoss, takeProfit)

// plot(fastEma, color = color.new(color.green, 0))
// plot(slowEma, color = color.new(color.red, 0))


// // longCondition = ta.crossover(ta.sma(close, 14), ta.sma(close, 28))
// // if (longCondition)
// //     strategy.entry("My Long Entry Id", strategy.long)

// // shortCondition = ta.crossunder(ta.sma(close, 14), ta.sma(close, 28))
// // if (shortCondition)
// //     strategy.entry("My Short Entry Id", strategy.short)


